### ISSUE TITLE
Error while setting up google_keep platform for sensor

### ISSUE THREAD

**Issue by superharaldsson** [PiotrMachowski/Home-Assistant-custom-components-Google-Keep#12]
Have worked but now have got this error and I do not get it to work again. what should I do?
installed through hacs 
version: 1.0.1

Error while setting up google_keep platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/google_keep/sensor.py", line 39, in setup_platform
    login_success = keep.login(username, password)
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 695, in login
    self.load(auth, state, sync)
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 741, in load
    self.sync(True)
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 996, in sync
    changes = self._reminders_api.list()
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 595, in list
    json=params
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 229, in send
    raise exception.APIException(error['code'], error)
gkeepapi.exception.APIException: {'errors': [{'domain': 'global', 'reason': 'forbidden', 'message': 'Forbidden'}], 'code': 403, 'message': 'Forbidden'}

**Comment by PiotrMachowski** [comment]
Please checki if error still exists in the v1.0.2

**Comment by superharaldsson** [comment]
Works like a charm, Thank you very much
