### ISSUE TITLE
Google Cape sensor not working

### ISSUE THREAD

**Issue by Roei639** [PiotrMachowski/Home-Assistant-custom-components-Google-Keep#15]
Google Keep sensor not working

Logger: homeassistant.components.sensor
Source: custom_components/google_keep/sensor.py:39
Integration: חיישן (documentation, issues)
First occurred: 13:51:34 (1 occurrences)
Last logged: 13:51:34

Error while setting up google_keep platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/google_keep/sensor.py", line 39, in setup_platform
    login_success = keep.login(username, password)
  File "/usr/local/lib/python3.8/site-packages/gkeepapi/__init__.py", line 693, in login
    ret = auth.login(username, password, get_mac())
  File "/usr/local/lib/python3.8/site-packages/gkeepapi/__init__.py", line 59, in login
    raise exception.LoginException(
gkeepapi.exception.LoginException: ('BadAuthentication', None)

**Comment by PiotrMachowski** [comment]
Have it worked before?
Which version of python do you have?
Do you use 2FA?
Do you use app password?

**Comment by Roei639** [comment]
Have it worked before?  - yes
Which version of python do you have? - python 3.8.5
Do you use 2FA? - yes
Do you use app password? - yes

**Comment by Roei639** [comment]
1. Yes
2. Python 3.8.5
3. Yes
4. Yes

**Comment by PiotrMachowski** [comment]
You can check out [this thread](https://github.com/kiwiz/gkeepapi/issues/81), maybe some solution will work for you (I would start with captcha)

**Comment by Roei639** [comment]
There is no solution.  Disable 2FA verification did not help either.

**Comment by PiotrMachowski** [comment]
This integration uses unofficial API, so maybe Google somehow blocks it in some conditions... It's really hard to say

**Comment by Roei639** [comment]
A few days ago it worked for me ...
I see I have more sensors that are not working and a similar error
Maybe related to Python?

**Comment by PiotrMachowski** [comment]
Has anything in your HA changed in a meantime?

**Comment by Roei639** [comment]
Update Version 0.118.2

**Comment by PiotrMachowski** [comment]
How is your HA installed?

**Comment by Roei639** [comment]
Docker

**Comment by thorin8k** [comment]
Same problem here, working nicely until update HA to 0.118. Since then the sensor keeps saying BadAuthentication when system starts.

**Comment by PiotrMachowski** [comment]
Can you manually change `manifest.json` file to this version:
```
{
  "domain": "google_keep",
  "name": "Google Keep",
  "documentation": "https://github.com/PiotrMachowski/Home-Assistant-custom-components-Google-Keep",
  "dependencies": [],
  "codeowners": ["@PiotrMachowski"],
  "requirements": ["gkeepapi==0.13.1"]
}
``` 
then restart HA and check if sensor is working?

**Comment by Roei639** [comment]
Does not work

**Comment by thorin8k** [comment]
Same here, updated gkeepapi to 0.13.1 via manifest and same exception. I will try again the captcha thing and see if it helps.

**Comment by PiotrMachowski** [comment]
I'm afraid I can't do anything more for now

**Comment by superharaldsson** [comment]
The same for me! No fix yet? 

Home Assistant 0.118.2

**Comment by Ameglialuna** [comment]
Same problem.

Home Assistant 0.118.2

**Comment by superharaldsson** [comment]
Same in 0.118.3

**Comment by Funcy-dcm** [comment]
Same problem

**Comment by Bird55** [comment]
Same in 0.118.4

**Comment by txusebe** [comment]
same in 0.118.5

**Comment by txusebe** [comment]
it works, 
pip install requests 2.25.0
pip install oauthlib 3.1.0
pip install requests-oauthlib 1.3.0

**Comment by homp** [comment]
Installed the 3 python modules mentioned above in the homeassistant venv, still getting the error:

gkeepapi.exception.LoginException: ('BadAuthentication', None)

HA 0.118.4

**Comment by superharaldsson** [comment]
> Installed the 3 python modules mentioned above in the homeassistant venv, still getting the error:
> 
> gkeepapi.exception.LoginException: ('BadAuthentication', None)
> 
> HA 0.118.4

Same for me

**Comment by LukaszP2** [comment]
Same ;/ 2020.12.0

**Comment by txusebe** [comment]
same in 2020.12.1 but i fix it with pyatmo one more time

pip install -U --force-reinstall pyatmo

**Comment by Scags104** [comment]
how do you run the pip command on an rpi4 running HA? i have the terminal open but wont let me....

**Comment by STiCory** [comment]
I'm getting the same exact error:
TrueNas 12.0-U1 running a 12.1-RELEASE-p12 jail
Home Assistant 2020.12.1
Python 3.8.6
HA google keep integration V1.1.0
GKEEPAPI 0.13.3
![image](https://user-images.githubusercontent.com/10111499/102747469-56dfdb80-432e-11eb-97dd-e21971e82ada.png)

**Comment by cokeman0** [comment]
anyone found a solution for this ? I can't get it working

**Comment by krelltunez** [comment]
I just installed the add-on via HACS.  I entered the info in my config.yaml file, and I'm getting the exact same error as the first post.  I'm on Home Assistant 2021.1.0 (on a Raspberry Pi).

I have NO IDEA how to even run the pip commands on the Raspberry Pi; based on some research I understand it is not possible.

> update: figured out i was using the wrong terminal. ran the command, reboot and..... still an error

@Scags104 what do you mean "the wrong terminal?"  How did you run the command?

Thanks all.

**Comment by Scags104** [comment]
There is another add-on with a similar name that allows it

**Comment by zevulos** [comment]
I have tried all the steps above and still have this problem, please update us when the API is working

**Comment by Funcy-dcm** [comment]
2021.2.2 - working again! But I changed the password on my google account

**Comment by mac00daddy** [comment]
I just installed this integration and front end card via HACS in HA 2022.3.6.  Initially I used the same app pw I had created for HA to send email notifications via my GMail account.  I wasn't seeing any errors, but the state of the sensor entity was 0 and it didn't show any of my Keep Notes.  I created a new Google app password and set the sensor to use it.  It now shows all of my notes under the sensor attributes and the state is > 0.
