### ISSUE TITLE
Sensor not working since 2022.04

### ISSUE THREAD

**Issue by maymaymay** [PiotrMachowski/Home-Assistant-custom-components-Google-Keep#26]
There is no sensor created.
Log shows:

Logger: homeassistant.components.sensor
Source: custom_components/google_keep/sensor.py:39
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: April 11, 2022, 13:21:52 (1 occurrences)
Last logged: April 11, 2022, 13:21:52

> Logger: homeassistant.components.sensor
> Source: custom_components/google_keep/sensor.py:39
> Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
> First occurred: April 11, 2022, 13:21:52 (1 occurrences)
> Last logged: April 11, 2022, 13:21:52
> 
> Error while setting up google_keep platform for sensor
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
>     await asyncio.shield(task)
>   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/google_keep/sensor.py", line 39, in setup_platform
>     login_success = keep.login(username, password)
>   File "/usr/local/lib/python3.9/site-packages/gkeepapi/__init__.py", line 693, in login
>     ret = auth.login(username, password, get_mac())
>   File "/usr/local/lib/python3.9/site-packages/gkeepapi/__init__.py", line 59, in login
>     raise exception.LoginException(
> gkeepapi.exception.LoginException: ('NeedsBrowser', 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.')

**Comment by k825k** [comment]
same problem... Please tell me how to resolve
APP password has already been set.

**Comment by adlpharm** [comment]
same here. Not working

**Comment by VaillantHassIo** [comment]
thought the update was the cause but there seems to be some changes on Googles end -.-
See: https://github.com/kiwiz/gkeepapi/issues/123

**Comment by TomCasavant** [comment]
It looks like they've got a solution for it using OAuth urls https://github.com/simon-weber/gpsoauth/pull/41

I assume we can just send this url in a notification when the integration is started?

**Comment by Roei639** [comment]
> This is an individual problem, check out this issue: [kiwiz/gkeepapi#20](https://github.com/kiwiz/gkeepapi/issues/20)

Hello,
Do you have a solution as well?  See the solution attached at the link:
https://github.com/simon-weber/gpsoauth/pull/42

**Comment by VaillantHassIo** [comment]
Will the 2022.06.01 Release with its OAuth2 Streamline help to fix this?

**Comment by Roei639** [comment]
> Will the 2022.06.01 Release with its OAuth2 Streamline help to fix this?

It's currently working

**Comment by VaillantHassIo** [comment]
yes after upgrading to 2022.06.01 it is working again! any explanation and will this last for long?

**Comment by PiotrMachowski** [comment]
It's possible that it is caused by a changing version of some library...

**Comment by gpitel** [comment]
I have been seeing a lot of comments about using Lynx (linux text browser) to authenticate a computer with google.  Unfortunately I am using Hassio, and it does not appear I have access to install such a browser.

https://github.com/kiwiz/gkeepapi/issues/32#issuecomment-406453756

**Comment by gpitel** [comment]
Seems like the error started as soon as Google mandated App Passwords
https://support.google.com/accounts/answer/6010255
I am using the App Password and it is still not working (getting same error posted in first comment).

**Comment by slyticoon** [comment]
Any update on the status of this issue?

**Comment by PiotrMachowski** [comment]
> yes after upgrading to 2022.06.01 it is working again! any explanation and will this last for long?
