### ISSUE TITLE
Error: NeedsBrowser

### ISSUE THREAD

**Issue by Cassock** [PiotrMachowski/Home-Assistant-custom-components-Google-Keep#3]
Getting this when trying to set up the Google Keep sensor. Using Docker image on Synology host.
```Log Details (ERROR)
Thu Aug 15 2019 21:20:42 GMT-0400 (Eastern Daylight Time)
Error while setting up platform google_keep
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 149, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/google_keep/sensor.py", line 39, in setup_platform
    login_success = keep.login(username, password)
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 517, in login
    ret = auth.login(username, password, get_mac())
  File "/usr/local/lib/python3.7/site-packages/gkeepapi/__init__.py", line 53, in login
    raise exception.LoginException(res.get('Error'), res.get('ErrorDetail'))
gkeepapi.exception.LoginException: ('NeedsBrowser', 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.')```

**Comment by PiotrMachowski** [comment]
If you have 2FA enabled you have to use App Password to get this integration working. Guide: https://support.google.com/accounts/answer/185833

**Comment by Cassock** [comment]
Perfect. I'm up!
