### ISSUE TITLE
Stop Working

### ISSUE THREAD

**Issue by milandzuris** [PiotrMachowski/Home-Assistant-custom-components-Google-Keep#31]
Integration Stop Working, have problem with login to google, i think is good make new integration and setup from UI.

**Comment by BebeMischa** [comment]
```
Logger: homeassistant.components.sensor
Source: custom_components/google_keep/sensor.py:39
Integration: Sensor (documentation, issues)
First occurred: 6 mei 2023 om 03:33:03 (1 occurrences)
Last logged: 6 mei 2023 om 03:33:03

Error while setting up google_keep platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/google_keep/sensor.py", line 39, in setup_platform
    login_success = keep.login(username, password)
  File "/usr/local/lib/python3.10/site-packages/gkeepapi/__init__.py", line 693, in login
    ret = auth.login(username, password, get_mac())
  File "/usr/local/lib/python3.10/site-packages/gkeepapi/__init__.py", line 59, in login
    raise exception.LoginException(
gkeepapi.exception.LoginException: ('BadAuthentication', None)
```

**Comment by milandzuris** [comment]
> ```
> Logger: homeassistant.components.sensor
> Source: custom_components/google_keep/sensor.py:39
> Integration: Sensor (documentation, issues)
> First occurred: 6 mei 2023 om 03:33:03 (1 occurrences)
> Last logged: 6 mei 2023 om 03:33:03
> 
> Error while setting up google_keep platform for sensor
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
>     await asyncio.shield(task)
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/google_keep/sensor.py", line 39, in setup_platform
>     login_success = keep.login(username, password)
>   File "/usr/local/lib/python3.10/site-packages/gkeepapi/__init__.py", line 693, in login
>     ret = auth.login(username, password, get_mac())
>   File "/usr/local/lib/python3.10/site-packages/gkeepapi/__init__.py", line 59, in login
>     raise exception.LoginException(
> gkeepapi.exception.LoginException: ('BadAuthentication', None)
> ```
> 
> @PiotrMachowski , would you please have a look in to this? Thank you very much in advance. ;-)

same

**Comment by superharaldsson** [comment]
Same here!

**Comment by yjamal01** [comment]
same issue here since 2023.5

**Comment by AlexKusnezov** [comment]
same here

**Comment by milandzuris** [comment]
this problem i have last month i think from core 2023.4

**Comment by milandzuris** [comment]
you start working on this problem or is time to delete? (question) thx

**Comment by PiotrMachowski** [comment]
> you start working on this problem or is time to delete? (question) thx

Huh? I'm not sure what you mean.

I have confirmed that this problem exists on my instance as well. I suspect this issue has been caused by upgrade of `requests` library. This integration uses [gkeepapi](https://github.com/kiwiz/gkeepapi) library and it seems to be highly dependent on version of `requests`.

**Comment by BebeMischa** [comment]
So, @PiotrMachowski , do we need to check/update something in our systems, or is it something you would need to take care of?
If we can fix it our self, fine, if we just do know how... ;-)

**Comment by PiotrMachowski** [comment]
No, you can't fix it. I'm not sure if I can fix it, as it seems to be a problem with a library that I use

**Comment by BebeMischa** [comment]
Well, then I just wish you the strength to over-win this ;-) Will wait quietly with hope on my mind ;-)

**Comment by cagarrinho** [comment]
Same here! @PiotrMachowski 
I sincerely hope you can help us. this integration of yours is very important to me. Thank you very much.

**Comment by TristanHoogmoed** [comment]
I'd be happy if this is gonna be fixed :)

**Comment by ostracizado** [comment]
Would it be possible to use the master token, instead?

Seems it was the work around for other custom integrations, such as @leikoilja's [ha-google-home](https://gist.github.com/rithvikvibhu/952f83ea656c6782fbd0f1645059055d).

**Comment by PiotrMachowski** [comment]
@ostracizado it should be possible [documentation](https://gkeepapi.readthedocs.io/en/latest/#logging-in)

**Comment by Roei639** [comment]
I have the same problem, is there a solution?

**Comment by biejay** [comment]
Same here

**Comment by slake119** [comment]
Is there a hope this is going to be resolved or is the project dead now?

**Comment by PiotrMachowski** [comment]
@slake119 There is a hope, but I don't have much time at this moment.

**Comment by BebeMischa** [comment]
So, should I now declare this card not reliable enough and look for a different approach? It now takes too long... ;-)

**Comment by AFumi39** [comment]
> So, should I now declare this card not reliable enough and look for a different approach? It now takes too long... ;-)

Let me know if you find a different method do manage GKeep lists on HA, please.
Now that Google dismissed 3rd party list integration from Assistant, I had to come back to GKeep and there's no working integration :(

PS: I will abandon any Google product as soon as possible.  No improvements, only removed features, lot of EOL, no support, nothing that works well, many bugs, etc

**Comment by BebeMischa** [comment]
that's, what I mean. I will just look for completely another solution. Bye bye Google Keep... ;-)

**Comment by PiotrMachowski** [comment]
> that's, what I mean. I will just look for completely another solution. Bye bye Google Keep... ;-)

It might be a good idea - this integration uses a library that uses an unofficial way to get data from GKeep, so there's absolutely no guarantee. Additionally it constantly keeps on breaking on changes of underlying libraries/python versions.

**Comment by milandzuris** [comment]
> Áno, používam Bring! od pár mesiacov práve teraz. Oveľa lepšie ako Keep (ale je tu aj AnyList a podobne). S poslednými zmenami Asistenta Google však od dnešného dňa už nie sú podporované vlastné nákupné zoznamy. Musíte používať službu Google Keep, takže sa snažím nájsť spôsob, ako sa spojiť s aplikáciou Keep a možno ju synchronizovať s aplikáciou Bring

same

**Comment by ELind77** [comment]
I have the same problem.

Cross-listing the dependency issue ticket for visibility: https://github.com/simon-weber/gpsoauth/issues/48

**Comment by CodeNeedsCoffee** [comment]
> > you start working on this problem or is time to delete? (question) thx
> 
> Huh? I'm not sure what you mean.
> 
> I have confirmed that this problem exists on my instance as well. I suspect this issue has been caused by upgrade of `requests` library. This integration uses [gkeepapi](https://github.com/kiwiz/gkeepapi) library and it seems to be highly dependent on version of `requests`.

What version of requests is your integration dependent on? I'm wondering if it would be possible to maybe have a local version of the requests library for the specific version the integration requires and import it from a local source for this specific integration..?

**Comment by PiotrMachowski** [comment]
At this moment integration uses version that is installed by HA (`requests==2.31.0` for `HA 2023.7.3`)

**Comment by elfux** [comment]
so, still not working? thanks!

**Comment by AFumi39** [comment]
> At this moment integration uses version that is installed by HA (`requests==2.31.0` for `HA 2023.7.3`)

I was on 2023.7.3, but I had to remove the component because it broke the official Gauge.

**Comment by superharaldsson** [comment]
Is there any hope of getting it going again? Or should I start looking for other options?

**Comment by CodeNeedsCoffee** [comment]
Just wanted to chime in here with my personal "hot take"; I did try to create a specific docker image that individuals could use that would host the correct version of the libraries and rebuild the HA integration to use this new docker, but after reviewing the gkeepapi and eventually getting the docker to work, I realized that there are some security flaws with this approach so I decided to not pursue the project any further. I will be working on a new one since I'm still determined to integrate Google Keep with Home Assistant, but I do not believe this specific component will be coming back to life in the near future.

**Comment by PiotrMachowski** [comment]
@CodeNeedsCoffee what have you changed to make it work?

**Comment by jgkawell** [comment]
Any update on this? I have the same use case as others where I wish to use Google Assistant to maintain grocery lists in Keep and sync with Home Assistant. Is there a path forward with the current integration? If someone has a path in the right direction I'm open to attempting a fix.

**Comment by CodeNeedsCoffee** [comment]
The unfortunate part is that Google only allows API access for
enterprise/business level accounts and not for consumer level accounts.
Recreating a working API has proven to have multiple road blocks depending
on different forms of authentication. We could just use an app password but
I personally don't like that approach and feel like it's less secure. With
that being said, I am actively working on a replacement component but
currently don't have anything to show.

**Comment by tjorim** [comment]
Feel free to Google how to use git/GitHub. Basically fork this repo, make the code adjustments, push it and open a PR.

**Comment by StefanoGiu** [comment]
Done

**Comment by PiotrMachowski** [comment]
Thanks @StefanoGiu, I'll check it out 👍
